= Repurpose Project - How to Repurpose, Reuse, Recycle and Organize
Further Info <info@repurposeproject.org>
:toc:
:icons: font

== Introduction
In this guide, you will learn how to 
[square]
* prepare items to be put out on the floor
* repurpose broken or worn items for functionality and art
* fix items

=== General Tips
. If something is messy, clean it. This includes wiping off dirt and dust from products, folding cloth instead of bundling it, wrapping cords properly, picking up after yourself, and picking up after others.
. Put things back where you found them. Tools can easily wander off or be misplaced. Floor items should be where both you and the customer expects them to be.
. Follow the systems already in place, but do not be afraid to suggest new ones. Again, organization makes for happy volunteers and happy customers. 
 
== Electronics
Congratulations, you've been selected to help in the *Electronics* section. Don't worry, it's not as scary as it looks (just don't get electrocuted).

=== Testing Procedures
. Clean the item. Wipe off any dust with a clean rag. Check for broken components (broken tape-deck doors, missing buttons, loose hinges, etc)
. Note any damaged or broken components.
. Wrap the cord using a rubber band. If the item is an AC adapter, rubber band the wrapped cord to the adapter body. If the item is a device, use your discretion to rubber band the cord to the device. 
[TIP]
Most cords will have bends from former wrappings. Try to stay in line with these. If such bends do not exist, wrap the cord either around your hand or in your hand - the wrapped loop should be no longer than 6". 
[WARNING]
DO NOT force bends in cables. DO NOT bend the cord sharply from its attachment point. Any sharp bends may damage the wiring. 
[WARNING]
DO NOT wrap the cable simply using itself. Such arrangments are prone to unwrapping, look messy and lack uniformity. In addition, by creating different shapes with odd bits sticking out, items are less likely to fit nicely on the shelf.
. If the item is not considered sellable - that is, the defects are major or interefere with normal operation -- see <Teardown Procedures>.
. Plug it in! Check that the item powers on. You may need to gather auxillary materials to test the item. For example, a stereo system will need speakers, a computer will need a monitor/keyboard/mouse, speakers will need an audio source, etc. Most of these items should be available in the testing station.
. Test features, where reasonable. For example, with tape decks, check: play, pause, stop, rewind, and fast foward functions. Note any broken features.
. If you've gotten this far, clearly label the item as "Working" or "Tested", with an additional label for any damages or lack of functionality.
. Place the item in the Outbox for placement on the floor.

=== Teardown Procedures
Once labelled damaged, irrepairable or broken, items should be broken down into components. Sometimes this may mean disassembling the item. _Gather your tools beforehand - you will probably need a phillips screwdriver, a flat head screwdriver and some wire cutters._

.For Cables
. Clip each end of the cable off, leaving a tail of 2-3" on each cable end. The tail will give artists and electricians something to work with. 
. Put the cable, without ends, in either the bulk wire section or the wire recycling section. 

.For devices
. Unscrew the faceplate or covering. Examine components.
[WARNING]
Some larger items, like CRT televisions and other displays, may contain components that can hold electrical charge (capacitors). Be careful and heed any warnings you find inside the device.
. Pull out circuit boards, LEDs, motors and any other individual components. Remember, this is mostly to create a pool for artists and electricians - think creatively!
. Place any left over materials -- plastic housing, wires, etc -- in the appropriate place. Wires can be reused or recycled, plastics can be added to the Plastics section, etc.

=== Placement
When in doubt, like goes with like! Kitchen electronics should go in the Kitchen section, CD players in the Audio section, computer peripherals in the Computer section, etc. When putting an item on the shelf, make sure it is easy to get to and inspect without creating a mess -- that is, don't stack small things, do put small things in bins or on hangers. 


== Conclusion
You should now be familiar with the operating procedures and guidelines for the Repurpose Project. Now you can help organize, fix and repurpose almost anything. Happy trails!
